gui:
  theme:
    activeBorderColor:
      - '#61afef'
      - 'bold'
    inactiveBorderColor:
      - '#abb2bf'
    optionsTextColor:
      - '#61afef'
    selectedLineBgColor:
      - '#2c323c'
    cherryPickedCommitBgColor:
      - '#c678dd'
    cherryPickedCommitFgColor:
      - '#61afef'
    unstagedChangesColor:
      - '#e06c75'
    defaultFgColor:
      - '#abb2bf'
    searchingActiveBorderColor:
      - '#e5c07b'
