# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #DEE3D4
background         #000102
cursor             #A2A69A

active_tab_foreground     #000102
active_tab_background     #DEE3D4
inactive_tab_foreground   #DEE3D4
inactive_tab_background   #000102

active_border_color   #DEE3D4
inactive_border_color #000102
bell_border_color     #403D37

color0      #000102
color1		#403D37
color2		#4C4F48
color3		#54564A
color4		#656A5A
color5		#656A5A
color6		#788263
color7		#C7CEB9
color8		#8B9082
color9		#56514A
color10		#666A60
color11		#707263
color12		#878D78
color13		#878D78
color14		#A0AE84
color15		#C7CEB9
