# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(000102)
$foreground = rgb(DEE3D4)
$color0 = rgb(000102)
$color1 = rgb(403D37)
$color2 = rgb(4C4F48)
$color3 = rgb(54564A)
$color4 = rgb(656A5A)
$color5 = rgb(656A5A)
$color6 = rgb(788263)
$color7 = rgb(C7CEB9)
$color8 = rgb(8B9082)
$color9 = rgb(56514A)
$color10 = rgb(666A60)
$color11 = rgb(707263)
$color12 = rgb(878D78)
$color13 = rgb(878D78)
$color14 = rgb(A0AE84)
$color15 = rgb(C7CEB9)
